CREATE TABLE IF NOT EXISTS socks
(
    id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    color       varchar(127),
    cotton      integer,
    quantity    integer,
    CONSTRAINT uq_color_cotton UNIQUE (color, cotton)
);